notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"

language: python
python:
  - "2.7"

env:
  - NUMPY_VERSION="==1.9.0"
  - NUMPY_VERSION=">=1.10"

before_install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install --upgrade pytest
  - pip install --upgrade "numpy$NUMPY_VERSION"

install:
  - python setup.py install

script:
  - py.test tests
  - flake8 .
